src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ReservationRepository::class)]
class Reservation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Assert\Range( min : "today",notInRangeMessage : "The date must be minimum today " )]
    private ?\DateTimeInterface $dateResevation = null;


    #[ORM\Column]
    #[Assert\NotBlank(message: "Le nombre de billets est obligatoire")]
    #[Assert\Positive(
        message: 'La valeur doit être positive.',
    )]
    private ?int $nombreBillet = null;

    
    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'reservation')]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'reservation')]
    private ?MatchF $matchF = null;

    /**
    * @ORM\OneToMany(targetEntity="App\Entity\Billet", mappedBy="reservation", cascade={"remove"})
    */
    private Collection $billet;

    #[ORM\Column(length: 255)]
    private ?string $Etat = null;

    public function __construct()
    {
        $this->matchFs = new ArrayCollection();
        $this->billet = new ArrayCollection();
        
        
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateResevation(): ?\DateTimeInterface
    {
        return $this->dateResevation;
    }

    public function setDateResevation(\DateTimeInterface $dateResevation): self
    {
        $this->dateResevation = $dateResevation;

        return $this;
    }

   
    public function getNombreBillet(): ?int
    {
        return $this->nombreBillet;
    }

    public function setNombreBillet(int $nombreBillet): self
    {
        $this->nombreBillet = $nombreBillet;

        return $this;
    }


    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getMatchF(): ?MatchF
    {
        return $this->matchF;
    }

    public function setMatchF(?MatchF $matchF): self
    {
        $this->matchF = $matchF;

        return $this;
    }

    /**
     * @return Collection<int, Billet>
     */
    public function getBillet(): Collection
    {
        return $this->billet;
    }

    public function addBillet(Billet $billet): self
    {
        if (!$this->billet->contains($billet)) {
            $this->billet->add($billet);
            $billet->setReservation($this);
        }

        return $this;
    }

    public function removeBillet(Billet $billet): self
    {
        if ($this->billet->removeElement($billet)) {
            // set the owning side to null (unless already changed)
            if ($billet->getReservation() === $this) {
                $billet->setReservation(null);
            }
        }

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->Etat;
    }

    public function setEtat(string $Etat): self
    {
        $this->Etat = $Etat;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Scheb\TwoFactorBundle\Model\Totp\TotpConfiguration;
use Scheb\TwoFactorBundle\Model\Totp\TotpConfigurationInterface;
use Scheb\TwoFactorBundle\Model\Totp\TwoFactorInterface;
use symfony\Component\Serializer\Annotation\Groups;
#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]


class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column, Groups('user')]
    private ?int $id = null;

    #[ORM\Column(type: 'json')]
    private array $roles = [];

    /**
     * @var string The hashed password
     */

    #[ORM\Column(nullable: true), Groups('user')]
    private ?string $password = null;

    #[ORM\Column(nullable: true), Groups('user')]
    private ?string $token = null;
/**
 * @Assert\Email(message="The email '{{ value }}' is not a valid email address.")
 */
    #[ORM\Column(length: 255,nullable: true), Groups('user')]
    private ?string $email = null;

    #[ORM\OneToMany(targetEntity:Commentaire::class, mappedBy: 'user')]

    private Collection $commentaire;

    #[ORM\OneToMany(targetEntity:Reservation::class, mappedBy: 'user')]
    private Collection $reservation;

    #[ORM\Column(length: 255, nullable:true)]
    private ?string $image = null;


    #[ORM\OneToMany(targetEntity:Reclamation::class, mappedBy: 'user')]

    private Collection $reclamation;

    #[ORM\Column(nullable: true), Groups('user')]
    private ?int $phone = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE), Groups('user')]
    private ?\DateTimeInterface $dateJoin = null;
 
    #[ORM\Column(name: 'googleId', type: 'integer', length: 255, nullable: true), Groups('user')]
    private ?string $googleId = null;


    #[ORM\Column(name: 'facebookId', type: 'integer', length: 255, nullable: true), Groups('user')]
    private ?string $facebookId = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: EventLike::class)]
    private Collection $eventLikes;
    // /**
    //  * @ORM\OneToOne(targetEntity=ConfirmToken::class, cascade={"persist", "remove"})
    //  * @ORM\JoinColumn(onDelete="SET NULL")
    //  */
    // private $token;

   
    #[ORM\Column(nullable: true), Groups('user')]
    private ?bool $banned = null;

    #[ORM\Column(type: 'boolean', nullable:true), Groups('user')]
    private $isVerified = false;


  #[Assert\Length(
     min: 2,
       max: 20,
     minMessage: 'Your first name must be at least {{ limit }} characters long',
       maxMessage: 'Your first name cannot be longer than {{ limit }} characters',
    )]
    #[ORM\Column(length: 255, nullable:true), Groups('user')]
    private ?string $firstName = null;

    #[Assert\Length(
        min: 2,
        max: 20,
        minMessage: 'Your second name must be at least {{ limit }} characters long',
        maxMessage: 'Your second name cannot be longer than {{ limit }} characters',
    )]
    #[ORM\Column(length: 255, nullable:true), Groups('user')]
    private ?string $secondName = null;
    
  
    public function __construct()
    {
        $this->commentaire = new ArrayCollection();
        $this->reservation = new ArrayCollection();
        $this->reclamation = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }
    public function serialize() {
        return serialize($this->id);
        }
    
        public function unserialize($data) {
        $this->id = unserialize($data);
        }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    public function setUsername(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return Collection<int, commentaire>
     */
    public function getCommentaire(): Collection
    {
        return $this->commentaire;
    }

    public function addCommentaire(commentaire $commentaire): self
    {
        if (!$this->commentaire->contains($commentaire)) {
            $this->commentaire->add($commentaire);
            $commentaire->setUser($this);
        }

        return $this;
    }

    public function removeCommentaire(commentaire $commentaire): self
    {
        if ($this->commentaire->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getUser() === $this) {
                $commentaire->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, reservation>
     */
    public function getReservation(): Collection
    {
        return $this->reservation;
    }

    public function addReservation(reservation $reservation): self
    {
        if (!$this->reservation->contains($reservation)) {
            $this->reservation->add($reservation);
            $reservation->setUser($this);
        }

        return $this;
    }

    public function removeReservation(reservation $reservation): self
    {
        if ($this->reservation->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getUser() === $this) {
                $reservation->setUser(null);
            }
        }

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection<int, reclamation>
     */
    public function getReclamation(): Collection
    {
        return $this->reclamation;
    }

    public function addReclamation(reclamation $reclamation): self
    {
        if (!$this->reclamation->contains($reclamation)) {
            $this->reclamation->add($reclamation);
            $reclamation->setUser($this);
        }

        return $this;
    }

    public function removeReclamation(reclamation $reclamation): self
    {
        if ($this->reclamation->removeElement($reclamation)) {
            // set the owning side to null (unless already changed)
            if ($reclamation->getUser() === $this) {
                $reclamation->setUser(null);
            }
        }

        return $this;
    }

    public function getPhone(): ?int
    {
        return $this->phone;
    }

    public function setPhone(int $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getDateJoin(): ?\DateTimeInterface
    {
        return $this->dateJoin;
    }

    public function setDateJoin(\DateTimeInterface $dateJoin): self
    {
        $this->dateJoin = $dateJoin;

        return $this;
    }

    public function isBanned(): ?bool
    {
        return $this->banned;
    }

    public function setBanned(bool $banned): self
    {
        $this->banned = $banned;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getSecondName(): ?string
    {
        return $this->secondName;
    }

    public function setSecondName(string $secondName): self
    {
        $this->secondName = $secondName;

        return $this;
    }

    /**
     * Get the value of googleId
     */ 
    public function getGoogleId()
    {
        return $this->googleId;
    }

    /**
     * Set the value of googleId
     *
     * @return  self
     */ 
    public function setGoogleId($googleId)
    {
        $this->googleId = $googleId;

        return $this;

src/Form/ReservationType.php
<?php

namespace App\Form;

use App\Entity\Reservation;
use App\Entity\User;
use App\Entity\MatchF;
use Symfony\Component\Form\AbstractType;
use App\Form\UserType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;


class ReservationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $user = $options['user'];
        $match = $options['matchF'];

        $builder
            ->add('nombreBillet')
            ->add('user', EntityType::class, [
                'class' => User::class,
                'data' => $user,
                'disabled' => true,
                'choice_label' => function ($user) {
                    return sprintf('%s, %s, %s', $user->getUserName(), $user->getEmail(), $user->getPhone());
                }
            ])
            ->add('Etat', HiddenType::class, [
                'data' => 'en attente', 
            ])
            ->add('save', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reservation::class,
            'user' => null,
            'matchF' => null,
        ]);
    }
}

templates/reservation/createR.html.twig
{% extends 'back.html.twig' %}

{% block main %}
<main id="main" class="main">
    <h1> Ajouter une réservation </h1>
    {{ form_start(f, { 'attr': {'novalidate': 'novalidate'}}) }}
    
        {{ form_label(f.nombreBillet, 'Nombre de billets') }}
        {{ form_widget(f.nombreBillet, { 'attr': {'class': 'form-control'} }) }}

   
    
    
    {{ form_end(f) }}
</main>    
{% endblock %}

templates/reservation/paiementReservation.html.twig
{% extends 'front.html.twig' %}

{% block banner %}
    <div class=innerbannerwrap>
        <div class=content></div>
        <div class=innerbanner><h2 class=bannerHeadline>Réserver <span>Billet</span></h2></div>
    </div>
{% endblock %}
{% block header %}
    <header class=header-main>
        <div class=header-upper>
            <div class=container>
                <div class=row>
                    <ul>
                        <li><a href="#">Signup/login</a></li>
                        <li><a href=shopcart.html><i class="fa fa-shopping-cart"></i> <span>cart(<span
                                class=cartitems>0</span>)</span></a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class=header-lower clearfix>
            <div class=container>
                <div class=row><h1 class=logo><a href=index-2.html><img src=assetsFront/images/tunisport.png alt=image></a></h1>

                    <div class=menubar>
                        <nav class=navbar>
                            <div class=nav-wrapper>
                                <div class=navbar-header>
                                    <button type=button class=navbar-toggle><span class=sr-only>Toggle navigation</span>
                                        <span class=icon-bar></span></button>
                                </div>
                                <div class=nav-menu>
                                    <ul class=nav navbar-nav menu-bar>
                                        <li><a href="{{path('front')}}" >Home <span></span> <span></span>
                                            <span></span> <span></span></a></li>
                                        <li><a href=about.html>about <span></span> <span></span> <span></span>
                                            <span></span></a></li>
                                        <li><a href="{{path('read_Event')}}">Event <span></span> <span></span> <span></span> <span></span></a>
                                            <ul class=sub-menu>
                                                <li><a href=gallerypage01.html>masonry</a></li>
                                                <li><a href=gallery02.html>gallery column two</a></li>
                                                <li><a href=gallery03.html>gallery column 03</a></li>
                                            </ul>
                                        </li>
                                        <li><a href=blog.html>blog <span></span> <span></span> <span></span>
                                            <span></span></a></li>
                                        <li><a href="{{path('read_Match')}}">Matchs <span></span> <span></span>
                                            <span></span> <span></span></a></li>
                                        <li><a href="#" class=active>réservation <span></span> <span></span> <span></span>
                                            <span></span></a></li>
                                        <li><a href=contact.html>contact <span></span> <span></span> <span></span>
                                            <span></span></a></li>
                                        {# <li><a>error <span></span> <span></span> <span></span> <span></span></a>
                                            <ul class=sub-menu>
                                                <li><a href=400.html>400 page</a></li>
                                                <li><a href=401.html>401 page</a></li>
                                                <li><a href=403.html>403 page</a></li>
                                                <li><a href=404.html>404 page</a></li>
                                                <li><a href=500.html>500 page</a></li>
                                                <li><a href=503.html>503 page</a></li>
                                            </ul>
                                        </li> #}
                                    </ul>
                                </div>
                            </div>
                        </nav>
                    </div>
                    <div class=social><a href=https://www.facebook.com/templatespoint.net class=facebook><i
                            class="fa fa-facebook"></i></a> <a href=https://twitter.com/itobuztech class=twitter><i
                            class="fa fa-twitter"></i></a> <a href=https://www.behance.net/ class=behance><i
                            class="fa fa-behance"></i></a></div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

{% block body %}
    <section class="innerpage_all_wrap bg-white">
        <div class=container>
            <div class=row><h2 class=heading>Paiement<span>Billet</span></h2>
                <div class=col>
                    <div class=contentinner>
                        <form action="{{ path("subscription_paiement", {'id': reservation.id }) }}" method="post" id="payment-form">
                            <div class="form-row">
                                <div id="card-elements"></div>

                                <script src="https://js.stripe.com/v3/"></script>

                                <div id="card-errors" role="alert"></div>
                            </div>
                            <div class=modal-footer>
                                <button class=btn-red>
                                    Acheter {{ reservation.matchF.prix }} DT
                                </button>
                            </div>    
                        </form>
                    </div>
                </div>
                
            </div>
        </div>
    </section>
{% endblock %}

{% block javascripts %}
<script src="{{asset('js/vendor/vendor.js')}}"></script>
<script src="{{asset('js/main.js')}}"></script>
<script>
    
    var stripeToken = "{{ stripe_public_key_test }}";
    
    var stripe = Stripe(stripeToken);
    var elements = stripe.elements();
    var subscription = "{{ reservation.id }}";
    var clientSecret = "{{ intentSecret }}";
    var cardholderName = "{{  app.user ? app.user.username : '' }}";
    var cardholderEmail = "{{ app.user ? app.user.email : ''  }}";
    
    console.log('clientSecret',clientSecret);

    var styleCustom = {
    	base: {
    		fontSize: '16px',
            
        }
    };

    var card = elements.create('card', {style: styleCustom });
    card.mount("#card-elements");
    //Message Error
    card.addEventListener('change', function(event){
    	var displayError = document.getElementById('card-errors');
    	if(event.error) {
		    displayError.textContent = event.error.message;
        } else {
		    displayError.textContent = '';
        }
    });
    var form = document.getElementById('payment-form');
    form.addEventListener('submit', function(event) {
    	event.preventDefault();
	    stripe.handleCardPayment(
		    clientSecret,
		    card,
             {
            	payment_method_data: {
		            billing_details: {
		            	name: cardholderName,
                        email: cardholderEmail
                    }
                }
            }
        ).then((result) => {
        	if(result.error) {
        		// Display error
            } else if('paymentIntent' in result) {
        		console.log('Result : ',result);
        		stripeTokenHandler(result.paymentIntent);
		        console.log('Result paymentIntent : ',result.paymentIntent);
            }
        })
    });
    function stripeTokenHandler(intent) {
    	var form = document.getElementById('payment-form');
    	var InputIntentId = document.createElement('input');
    	var InputIntentPaymentMethod = document.createElement('input');
	    var InputIntentStatus = document.createElement('input');
	    var InputSubscription = document.createElement('input');
	    InputIntentId.setAttribute('type', 'hidden');
	    InputIntentId.setAttribute('name', 'stripeIntentId');
	    InputIntentId.setAttribute('value', intent.id);
	    InputIntentPaymentMethod.setAttribute('type', 'hidden');
	    InputIntentPaymentMethod.setAttribute('name', 'stripeIntentPaymentMethod');
	    InputIntentPaymentMethod.setAttribute('value', intent.payment_method);
	    InputIntentStatus.setAttribute('type', 'hidden');
	    InputIntentStatus.setAttribute('name', 'stripeIntentStatus');
	    InputIntentStatus.setAttribute('value', intent.status);
	    InputSubscription.setAttribute('type', 'hidden');
	    InputSubscription.setAttribute('name', 'subscription');
	    InputSubscription.setAttribute('value', subscription);
	    form.appendChild(InputIntentId);
	    form.appendChild(InputIntentPaymentMethod);
	    form.appendChild(InputIntentStatus);
	    form.appendChild(InputSubscription);
	    form.submit();
    }
    
    
</script>
{% endblock %}

templates/reservation/readR.html.twig
{% extends 'back.html.twig' %}
{% block main %}
<main id="main" class="main">
    <section class="section">
        <div class="row">
          <div class="col-lg-12">
    
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">Liste des réservations</h5>
                
    
                <!-- Table with stripped rows -->
                <table class="table datatable">
                  <thead>
                    <tr>
                        <th scope="col" class="border-0 rounded-start">Référence_réservation</th>
                        <th scope="col" class="border-0">Date</th>
                        <th scope="col" class="border-0">Nombre de billets</th>
                        <th scope="col" class="border-0">Etat</th>
                        <th scope="col" class="border-0 rounded-end">Supprimer</th>
                        <th scope="col" class="border-0 rounded-end">Modifier</th>
                    </tr>
                  </thead>
                  {%  for r in  reservation %}
                <tbody>
                <!-- Table item -->
                <tr>
                    <td>
                        <div class="d-flex align-items-center">
                            <!-- Title -->
                            <h6 class="mb-0 ms-2 table-responsive-title">
                                <a href="#">{{ r.id }}</a>
                            </h6>
                        </div>
                    </td>
                    <td>{{ r.dateResevation.format('d/m/Y') }}</td>
                    <td>{{ r.nombreBillet }}</td>
                    <td>{{ r.Etat }}</td>
            
                    <!-- Action item -->
                    <td><form action="{{ path('deleteReservation', {id:r.id}) }}">
                      <button  class="btn btn-danger"><i class="bi bi-trash"></i>supprimer</button>
                  </form> </td>
                  <td><form action="{{ path('updateReservation', {id:r.id}) }}">
                    <button  class="btn btn-success"><i class="bi bi-pen-fill"></i>modifier</button>
                </form> 
               </td>
                
                </tbody>
                {% endfor %}
                </table>
    
              
            
    
          </div>
        </div>
      </section>
    
    </main><!-- End #main -->
{% endblock %}

templates/reservation/reponsePaiement.html.twig
{% extends 'front.html.twig' %}

{% block banner %}
    <div class=innerbannerwrap>
        <div class=content></div>
        <div class=innerbanner><h2 class=bannerHeadline>Réserver <span>Billet</span></h2></div>
    </div>
{% endblock %}
{% block body %}
<section class="innerpage_all_wrap bg-white">
    
        

            <div class=container>
                <div class="col-md-6 mb-4">
                    <div class="card">
                        <div class="card-header">
                            <h4>
                                <strong> Paiement valide </strong>
                            </h4>
                        </div>

                        <div class="card-body">
                            <center>
                                <i class="fas fa-shield-alt orange-text fa-8x"></i>
                            </center>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 mb-4">
                    <div class="card">
                        <div class="card-header">
                            <h4>
                                <strong>Details Billet</strong>
                            </h4>
                        </div>

                        <div class="card-body">
                            <h3 class="card-title pricing-card-title mb-4"> Prix : {{ reservation.matchF.prix }} DT</h3>
                            
                    </div>
                </div>
            </div>

        </div>
    
</section>    
{% endblock %}

templates/reservation/updateR.html.twig
{% extends 'back.html.twig' %}

{% block main %}
<main id="main" class="main">
    <div class="card">
        <div class="card-body">
          <h5 class="card-title">Ajouter une réservation</h5>
    
          <!-- Multi Columns Form -->
          <form class="row g-3">
            {{ form_start(f, { 'attr': {'novalidate': 'novalidate'}}) }}
            <div class="col-md-12">
                {{ form_label(f.dateResevation, 'Date de réservation') }}
                {{ form_widget(f.dateResevation, { 'attr': {'class': 'form-control'} }) }}
            </div>
            <div class="col-md-6">
                {{ form_label(f.etat, 'Etat de la réservation') }}
                {{ form_widget(f.etat, { 'attr': {'class': 'form-control'} }) }}
            </div>
            <div class="col-md-6">
                {{ form_label(f.nombreBillet, 'Nombre de billets') }}
                {{ form_widget(f.nombreBillet, { 'attr': {'class': 'form-control'} }) }}
            </div>
            <div class="col-md-6">
                {{ form_label(f.matchF, 'Match associé') }}
                {{ form_widget(f.matchF, { 'attr': {'class': 'form-control'} }) }}
            </div>
            {{ form_end(f) }}
          </form>
    
        </div>
      </div>
</main>

{% endblock %}